class SignUpLocators:
    TITLE = "#id_gender1"
    NAME = "#name"
    LABEL_ACCOUNT_INFO = "div.login-form h2 b:has-text('Enter Account Information')"
    PASSWORD = "#password"
    DAYS = "#days"
    MONTHS = "#months"
    YEARS = "#years"
    FIRST_NAME = "#first_name"
    LAST_NAME = "#last_name"
    COMPANY_NAME = "#company"
    ADDRESS = "#address1"
    ADDRESS2 = "#address2"
    COUNTRY = "#country"
    STATE = "#state"
    CITY = "#city"
    ZIP_CODE = "#zipcode"
    MOBILE_NUMBER = "#mobile_number"
    CREATE_ACCOUNT = "button[data-qa='create-account']"
    # Add all the endpoints here for signup page
